---
title: "Examples of Customization"
output: pdf_document
---

#Exposure

##calc_t

```{r}
sintrend <- function(n, y){
  day <- c(1:n)
  1 + y * sin(2 * pi * (day / 365))
}
binsin <- function(n, y, p){
  day <- c(1:n)
  seasont <- p + y * sin(2 * pi * (day / 365))
}
calc_t(n = 5, y = .3, custom_func = sintrend)
plot(calc_t(1000, y = 2, custom_func = sintrend))
plot(bin_t(1000, p=.3, trend="cos1"))
plot(bin_t(1000, p=.3, custom_func=binsin, y=.1))
```

bin_t is similar.

##binary and continuous exposure

```{r}
binary_exposure(n=5, p = .2, y = .1, amp=.1, custom_func = sintrend)
plot(binary_exposure(n=1000, p = .1, y = .1, amp = .1, custom_func = sintrend))

continuous_exposure(n = 5, y = .6, mu = 100, sd = 10, custom_func = sintrend)
plot(continuous_exposure(n=1000, y = 1, mu = 200, sd = 50, custom_func = sintrend))
```

##Custom functions for outcome

```{r}
#For baseline:
custombase <- function(n, slope, intercept){
  day <- c(1:n)
  baseline <- day*slope + intercept
  return(baseline)
}

#Example
custombase(n=5, slope = .3, intercept = 55)

#For lambda:
customlambda <- function(exposure, rr, constant, baseline){
  log_lambda <- log(baseline) + log(rr) * exposure + constant
  lambda <- exp(log_lambda)
  return(lambda)
}

#Example:
testlambda <- customlambda(testexp$x, testbase$baseline, rr=1.01, constant = 4)
```

##Custom function for model

```{r}
trivial_mod <- function(df, constant){
  newx <- constant*df$x
  mod <- lm(outcome~newx, data=df)
  out_1 <- summary(mod)$coef[2, ]
  out_2 <- stats::confint.default(mod)[2, ]
  out <- c(out_1, out_2)
  return(out)
}
```
