---
title: "Outstanding Title"
author: "Sarah Koehler"
date: "February 21, 2017"
output:
  pdf_document: default
  html_document: default
---

#Introduction

Simulation studies are important in environmental epidemiology research on air pollution, temperature, and other exposures. For example, simulated data can be used to test new statistical models and perform power analyses. Two current challenges of simulating time series data for epidemiology studies are (1) methods for simulating are inconsistent, making it difficult to compare results from different studies, and (2) developing the code to simulate environmental time series for these types of studies can be time consuming. We introduce `eesim`, an open-source software package in R that offers a solution to these challenges.

Simulated data has been used in a number of environmental epidemiology studies on various kinds of exposures and outcomes. (citet{Armstrong2014}) used a simulation study to investigate short-term mortality displacement following heat waves. (citet{Bateson1999}), (citet{Bateson2001}), and (citet{Peng2006}) used simulated data with confounding seasonal trends to compare experimental designs and model choice. (citet{Strickland2015}), (citet{Gryparis2009}), and (citet{Butland2013}) investigated spatial misalignment and geographic heterogeneity of exposures using simulated data. (citet{Roberts2006}) used a simulation study to test the reliability of using AIC to determine the shape of the relationship between particulate matter and mortality. (citet{Bobb2015}) used simulation to assess the performance of a proposed method for estimating the health effects of multi-pollutant exposures called Bayesian kernel machine regression (BKMR). 

Here, we present an R package that automates simulation of environmental time series for such simulations, offering both sensible defaults for each stage of the simulation process and also the option to customize any of the simulation steps while using defaults for any steps that do not require customization. There are a few important advantages to having an open-source software package that can simulate this type of environmental time series for simulation studies. First, current methods of simulating environmental time series to use to assess modeling choices vary across different studies. If results from a simulation study are not robust to different choices in how to simulate the data used in the study, results across studies using different methods of simulating data would not be comparable \citep{Alfons2010}. 

This package offers several methods of simulating time series so researchers can check if study results are robust to data simulation method. This software also allows for consistency and comparison of data simulation across studies and will save researchers time and effort in developing study-specific code. This package can be used to aid simulation studies to explore environmental epidemiology models relating acute health outcomes and daily environmental exposures; it can also be used to estimate the power of studies when planning or proposing future research.

#Simulating Data and Testing Models

Simulation studies can be used to assess different models and modeling choices. This way of assessing models can be particularly useful for complex statistical methods, for which assessing performance metrics can often prove difficult (citep{Alfons2010}). The `eesim` package allows you to simulate time series of environmental health data and perform simulation-based power analyses and other measures of model performance. The package includes four main parts: 

1. Generation of exposure data; 
2. Generation of outcome data;
3. Fitting models to simulated data; and 
4. Evaluating model performance on simulated data.

The user has the option to customize different aspects of the simulation at each of these steps.

The main function of this package is the `eesim` function. You can use the `eesim` function to conduct all four steps of the simulation process outlined above at once. The `eesim` function requires several arguments, both numeric and character, including the desired number of repetitions of the simulation, the sample size for each repetiton, the type of exposure values (binary or continous), the expected average value of the response variable, the relative risk, and the type of model desired. The user has the option to input more arguments specifying trends or custom functions for the exposure, the outcome, or both.

The `eesim` function returns a list with two elements. The first element gives simulation-specific results: the estimated effect size, standard error, t- and p-values, and upper and lower 95% confidence bounds when a model was applied to each set of simulated data. The second element gives some measures of model assessment, assessed over all simulations, including the mean effect size and relative risk estimates across simulations.

[insert equation here?]

For example, you can use the following call to (1) generate 3 repetitions of 100 observations of a continuous exposure with mean 50 and standard deviation 5, with a seasonal trend in expected value; (2) generate 10 associated outcome values, where the outcome has an average value of 20 and a relative risk of 1.10 per one-unit increase in the exposure; (3) fit a generalized linear model that controls for long-term and seasonal trends with a natural cubic spline with 2 degrees of freedom per year; and (4) evaluate the performace of that model on the simulated data:

```{r}
library(eesim)
eesim(n_reps = 3, n = 100, central = 50, sd = 5, exposure_type = "continuous", 
      outcome_trend = "curvilinear", average_outcome = 20, rr = 1.10, model = "spline", df_year = 2)
```

The above output gives the estimated effect sizes for each of the three repetitions along with their standard errors, test statistics, p-values, and confidence intervals. It also summarizes the outcomes of all three repetitions with a mean estimated beta (which equals the log of the estimated relative risk), estimated relative risk, the variance of the estimated betas, and the mean variance of the individual betas.  

The `eesim` output also gives the relative parameter estimate bias, according to the following equation  from (citet{Beaujean2014}), given $\theta_{H}$ (true value of the parameter, as set when creating the simulated data) and $\hat{\theta}$ (value of the parameter estimated from applying a model to the simulated data): 

\begin{equation}
\theta_{bias} = \frac{\hat{\theta} - \theta_{H}}{\theta_{H}}
\end{equation}

Finally, the `eesim` output gives the coverage and power of the model.

#Power Analysis

Simulation studies can be used to determine effective sample size or power when planning or proposing future research studies. This method can be particularly useful in cases where modeling of the study data will be particularly complex and when the strong assumptions of classical, analytical power analysis are questionable (citep{Bellan2015, Johnson2015, Burton2009, Alfons2010, Beaujean2014}). Simulation studies can often be used to generate power analyses under a more realistic set of assumptions (citep{Burton2009, Beaujean2014}).
